### ISSUE TITLE
which version is supported on k8s 1.15

### ISSUE THREAD

**Issue by wwyhy** [kubernetes-sigs/azurefile-csi-driver#1397]
We have a k8s cluster with version 1.15 (set up by VMs/on-premise on azure) , now we need to support azure file and deploy azure-file-csi-driver on this cluster.
so which version is supported this version? 

latest doc is only for 1.21+. 

thanks!

**Comment by andyzhangx** [comment]
the initial supported version is k8s 1.16 from v1.0.0, not sure it could run will on 1.15, https://github.com/kubernetes-sigs/azurefile-csi-driver/tree/v1.0.0, and since you are using k8s 1.15, I think you could use azure file in-tree driver: https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/master/docs/driver-parameters-intree.md
https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/master/docs/intree-static-example.md

**Comment by wwyhy** [comment]
@andyzhangx 
I tried with the in-tree solution, but it seems it is hit this bug/issue(403 error) https://github.com/Azure/AKS/issues/804.

if I "allow all networks" in ""Firewalls and virtual networks", it works fine, but due to some reason, we have to disable "public network access" and create a priviate endpoint for it. 

so for this senario, is there any solution to make it works? 

thanks!

**Comment by andyzhangx** [comment]
the in-tree driver fix is on k8s 1.19 or install v1.0.0 azure file csi driver; you could also create file share in advance, and then use account name & key to access the file share, refer to https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/master/docs/intree-static-example.md#mount-file-share-as-an-inline-volume

**Comment by wwyhy** [comment]
I tried this way, but get "permission denied" during pod mount.
and will try to install 1.0.0 azure file csi driver, thanks!

**Comment by andyzhangx** [comment]
@wwyhy you need to add your node ip into the allowed network config.
