### ISSUE TITLE
add UT for createDisk func

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes-sigs/azurefile-csi-driver#181]
**Is your feature request related to a problem?/Why is this needed**

**Describe the solution you'd like in detail**

add UT for createDisk func, at least negative cases

https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/ea75bfe4cdde8b419e27667a1f8e9c63f7f8afc9/pkg/azurefile/azurefile.go#L350-L373

**Describe alternatives you've considered**

**Additional context**

**Comment by ZeroMagic** [comment]
Need to add a mock file Client in the fake cloud firstly. 
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/legacy-cloud-providers/azure/azure_fakes.go#L47

**Comment by kushthedude** [comment]
Hi @andyzhangx, I would like to solve this issue. Can you provide additional details on Unit Tests that need to be added for the following functions?

**Comment by andyzhangx** [comment]
@animeshk08 could you also take a look at this? thanks.

**Comment by animeshk08** [comment]
The unit tests already exist here: https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/f0a7d581749fd29fcb4340adceb2a63bebc929b3/pkg/azurefile/azurefile_test.go#L605

Line coverage can be found here: https://coveralls.io/builds/32107068/source?filename=pkg/azurefile/azurefile.go#L364

Only lines 384-387 are prominently remaining, which cannot yet be covered due to the absence of the mock interface(see [here](https://github.com/kubernetes-sigs/azurefile-csi-driver/issues/326#issuecomment-656195543)).

**Comment by andyzhangx** [comment]
thanks
