### ISSUE TITLE
1 node(s) didn't have free ports for the requested pod ports (csi controller replicas)

### ISSUE THREAD

**Issue by TaharInfo** [kubernetes-sigs/azurefile-csi-driver#742]
I deployed the CSI Driver on my AKS cluster with Terraform, but I had this error : 

`1 node(s) didn't have free ports for the requested pod ports`

because I have ONE system node, while in the helm chart it's indicated two (2) controller pod's replicas that apparently use the same health and metrics ports : 

image: mcr.microsoft.com/k8s/csi/azurefile-csi:latest
Ports: healthz:29612,metrics:29614

With two system nodes minimum, it works fine.
With controller.replicas=1 it works, but when I try to update the controller it failed because he tries to create a 2nd pod controller before deleting the old one, so the node didn't have free ports.

Thanks for your help.

K8S : 1.19.11
CSI Dirver : 1.5.0
Terraform : 1.0.1

**Comment by andyzhangx** [comment]
you need to delete the old controller pod when updating since you only have one node running controller pod. The main dependency is on `hostNetwork: true`, if your node is not using MSI(Managed Identity), it's ok to remove `hostNetwork: true` in the deployment.
I will add a customization for `controller.hostNetwork` setting in helm install later.

**Comment by andyzhangx** [comment]
https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/0e088bd2b744f8acc355073c70c4d42f7b8aa3fc/deploy/csi-azurefile-controller.yaml#L16-L17

**Comment by TaharInfo** [comment]
I didn't understand why these ports are fixed and not dynamic.
With a single system node, the problem is not only on the update but even on the first deployment of csi driver,
and I suppose that even with 2 nodes, we cannot do an update as it will create a 3rd pod before deleting the old one (port conflict on one of the system nodes)

In my case as I only have one system node, it doesn't work because of the healthz and metrics ports which are identical between the two replicas. 

I want to test: `controller.replicas=1` 
do you think that does not create problems ?

FYI, this is my Terraform code to deploy this Driver : 
```
resource "helm_release" "azurefile-csi-driver-helm" {
  name = "azurefile-csi-driver"
  repository = "https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts"
  chart      = "azurefile-csi-driver"
  version    = "1.5.0"
  namespace = "kube-system"
} 
```

**Comment by andyzhangx** [comment]
the issue is on `hostNetwork: true` setting, if that value is set as false, there won't be any issue. and you could `--set controller.metricsPort=xxx --set controller.livenessProbe.healthPort=xxx` to specify different port num in every version upgrade.

BTW, not sure how to assign a random port num in helm deployment.
