### ISSUE TITLE
Could not mount ... globalmount does not exist

### ISSUE THREAD

**Issue by GeertvanHorrik** [kubernetes-sigs/azurefile-csi-driver#875]
# What happened

1 node
5 pods
5 disks
5 pv
5 pvc

Relevant components:

## Component 1

Name: `component1-postgres`
Volumes: `component1-postgres-volume` (uses `component1-postgres-pvc`)

## Component 2

Name: `component2-postgres`
Volumes: `component2-postgres-volume` (uses `component2-postgres-pvc`)

# Error

All 5 disks are correctly attached to the VM in Azure. Only 1 pod is not working with the following error:

```
MountVolume.SetUp failed for volume "component2-postgres-pv" : rpc error: code = Internal desc = Could not mount "/var/lib/kubelet/plugins/kubernetes.io/csi/pv/component2-postgres-pv/globalmount" at "/var/lib/kubelet/pods/[POD_ID]/volumes/kubernetes.io~csi/component2-postgres-pv/mount": mount failed: exit status 32 Mounting command: mount Mounting arguments: -o bind /var/lib/kubelet/plugins/kubernetes.io/csi/pv/component2-postgres-pv/globalmount /var/lib/kubelet/pods/[POD_ID]/volumes/kubernetes.io~csi/component2-postgres-pv/mount Output: mount: /var/lib/kubelet/pods/[POD_ID]/volumes/kubernetes.io~csi/component2-postgres-pv/mount: special device /var/lib/kubelet/plugins/kubernetes.io/csi/pv/component2-postgres-pv/globalmount does not exist.
```

I found similar issues here:

#831 
#648
#620

# What you expected to happen

All volumes are unique (at least I think they are), so they should all be mounted. The mount paths are similar, but they are running on different pods so that should be irrelevant?

# How to reproduce it

The relevant configs are here (the resourceVersion and uid are generated by the system, but I included them as they show they are connected to the correct PV / PVC). As you can see, they are fairly similar (using a naming convention for all the names).

## Component 1

```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: component1-postgres-pv
  resourceVersion: "330270"
  uid: 09a24bcc-0bf0-4848-8609-26639374e94a
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: component1-postgres-pvc
    namespace: default
    resourceVersion: "330127"
    uid: b436167b-b006-40d8-9c8b-14f4ec0d11ab
  csi:
    driver: disk.csi.azure.com
    volumeAttributes:
      fsType: ext4
    volumeHandle: /subscriptions/[REDACTED]/resourceGroups/test05/providers/Microsoft.Compute/disks/test05-component1-postgres-disk
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
status:
  phase: Bound
    
-----

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: component1-postgres-pvc
  namespace: default
  resourceVersion: "330244"
  uid: b436167b-b006-40d8-9c8b-14f4ec0d11ab
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: component1-postgres-pv
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  phase: Bound
```

## Component 2

```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: component2-postgres-pv
  resourceVersion: "330508"
  uid: ff259ea3-3253-422a-89a8-c76b8b8c2e02
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: component2-postgres-pvc
    namespace: default
    resourceVersion: "330129"
    uid: 01b2c9cc-e093-4190-8dc6-ff8320dc65c9
  csi:
    driver: disk.csi.azure.com
    volumeAttributes:
      fsType: ext4
    volumeHandle: /subscriptions/[REDACTED]/resourceGroups/test05/providers/Microsoft.Compute/disks/test05-component2-postgres-disk
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
status:
  phase: Bound

-----

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: component2-postgres-pvc
  namespace: default
  resourceVersion: "330249"
  uid: 01b2c9cc-e093-4190-8dc6-ff8320dc65c9
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: component2-postgres-pv
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  phase: Bound
```

## Logging

```
I0106 15:45:38.331283 1 utils.go:95] GRPC call: /csi.v1.Node/NodePublishVolume
I0106 15:45:38.331310 1 utils.go:96] GRPC request: {"publish_context":{"LUN":"4","diskiopsreadwrite":"500","diskmbpsreadwrite":"60","networkaccesspolicy":"AllowAll","skuname":"Standard_LRS"},"staging_target_path":"/var/lib/kubelet/plugins/kubernetes.io/csi/pv/component2-postgres-pv/globalmount","target_path":"/var/lib/kubelet/pods/[POD_ID]/volumes/kubernetes.io~csi/component2-postgres-pv/mount","volume_capability":{"AccessType":{"Mount":{}},"access_mode":{"mode":1}},"volume_context":{"fsType":"ext4"},"volume_id":"/subscriptions/[REDACTED]/resourceGroups/test05/providers/Microsoft.Compute/disks/test05-component2-postgres-disk"}
I0106 15:45:38.331490 1 nodeserver.go:263] NodePublishVolume: mounting /var/lib/kubelet/plugins/kubernetes.io/csi/pv/component2-postgres-pv/globalmount at /var/lib/kubelet/pods/[POD_ID]/volumes/kubernetes.io~csi/component2-postgres-pv/mount
I0106 15:45:38.331514 1 mount_linux.go:183] Mounting cmd (mount) with arguments ( -o bind /var/lib/kubelet/plugins/kubernetes.io/csi/pv/component2-postgres-pv/globalmount /var/lib/kubelet/pods/[POD_ID]/volumes/kubernetes.io~csi/component2-postgres-pv/mount)
E0106 15:45:38.333503 1 mount_linux.go:195] Mount failed: exit status 32
Mounting command: mount
Mounting arguments: -o bind /var/lib/kubelet/plugins/kubernetes.io/csi/pv/component2-postgres-pv/globalmount /var/lib/kubelet/pods/[POD_ID]/volumes/kubernetes.io~csi/component2-postgres-pv/mount
Output: mount: /var/lib/kubelet/pods/[POD_ID]/volumes/kubernetes.io~csi/component2-postgres-pv/mount: special device /var/lib/kubelet/plugins/kubernetes.io/csi/pv/component2-postgres-pv/globalmount does not exist.
```

# Anything else we need to know?

**Environment**:
- CSI Driver version: 1.11
- Kubernetes version (use `kubectl version`): "v1.21.3+rke2r2"
- OS (e.g. from /etc/os-release): 
- Kernel (e.g. `uname -a`): Linux dashboard-shell-br8sg 5.11.0-1023-azure 24~20.04.1-Ubuntu SMP [REDACTED] x86_64 Linux
- Install tools: -
- Others: -

**Comment by andyzhangx** [comment]
do you have full logs of `csi-azuredisk-node` on the agent node? one `NodeStageVolume` action should be missing on the node, it's going to mount `/var/lib/kubelet/plugins/kubernetes.io/csi/pv/component2-postgres-pv/globalmount` on the node, usually it's caused by two PVs with same volumeHandle issue before.

**Comment by GeertvanHorrik** [comment]
I created a complete new cluster with disks and now it's working. Maybe there was something wrong with the initial disks / cluster. It seems to work correctly now.

**Comment by aarontravass** [comment]
Encountered this issue today on our k8s cluster (version: 1.23). Our set up is as follows:
1. Azure disk
2. 2 postgres deployments each having different PVs/PVCs. Each deployment is mounted to the same azure disk but different paths (something like `/mnt/azure/pg1` and `/mnt/azure/pg2`)

As a result, it had the same volume handle. Unfortunately, I do not believe the volume handle can be modified since azure explicitly specifies the volume handle to be of the following format:
```log
/subscriptions/{sub-id}/resourcegroups/{group-name}/providers/microsoft.compute/disks/{disk-id}
```
see -> https://learn.microsoft.com/en-us/azure/aks/azure-csi-disk-storage-provision#static-provisioning-parameters-for-a-persistent-volume

I tried playing around but couldn't get it to work. At the end, I simply upgraded our k8 cluster version to 1.28. Maybe it's a bug in 1.23 that got patched later? 

Hope this helps someone.

**Comment by andyzhangx** [comment]
@GeertvanHorrik k8s 1.23 is too old version, not sure how to debug since I could not create such an old version cluster, let me know if you hit the issue on k8s 1.28

**Comment by GeertvanHorrik** [comment]
My cluster is on 1.28.14, it happened again last night.

**Comment by andyzhangx** [comment]
@GeertvanHorrik what is your two PV config?

**Comment by GeertvanHorrik** [comment]
That's the other user, @aarontravass that is / was on an older version of K8S. You can see my PV / PVC configs at the initial post?

Note that I have just 1 pool. Once this pools receives a restart (because of auto-patched OS updates of Azure), it gets into an error state. The only solution I found so far is to restart (stop / start) the cluster.

**Comment by andyzhangx** [comment]
> That's the other user, @aarontravass that is / was on an older version of K8S. You can see my PV / PVC configs at the initial post?
> 
> Note that I have just 1 pool. Once this pools receives a restart (because of auto-patched OS updates of Azure), it gets into an error state. The only solution I found so far is to restart (stop / start) the cluster.

@GeertvanHorrik the CSI driver does not handle node reboot well, that's an upstream kubelet issue, and when your node is rebooted, could you reschedule the pods to other node first?

**Comment by mloskot** [comment]
@andyzhangx 
> @GeertvanHorrik the CSI driver does not handle node reboot well, that's an upstream kubelet issue,

I have experienced very similar issue three times over the last 7-10 days, i.e. pods running on the same Windows node, stop getting up  after node reboot due to 

```
MountVolume.MountDevice failed for volume "xxx-drive-l" :
  kubernetes.io/csi: attacher.MountDevice failed to create dir "\var\lib\kubelet\plugins\kubernetes.io\csi\disk.csi.azure.com\affd0f45538e9c7d78a1782c4313b3a787556f3fdbb1601e305edfa5dec73909\globalmount": 
  path \var\lib\kubelet\plugins\kubernetes.io\csi\disk.csi.azure.com\affd0f45538e9c7d78a1782c4313b3a787556f3fdbb1601e305edfa5dec73909\globalmount exists but is not a directory
```

where `xxx-drive-l` is Azure Disk which is mounted as volume by 2-4 pods running on that very same node.

The restarts of the node do not help - I guess due to the _"CSI driver does not handle node reboot well"_ and the only solution is to **reimage** the node VM. Unfortunately, I don't have detailed logs enabled for the VM-s, so I'm not able to provide any more details.

I wonder if there has been any update to the CSI driver/kubelet to make it more node reboot-proof.

I'm currently running AKS and nodes based on Kubernetes 1.30.11

**Comment by andyzhangx** [comment]
@mloskot the kubelet cannot handle volume reconstruct after node reboot, related issue: https://github.com/kubernetes/kubernetes/issues/117513, after node reboot, I think you need to reschedule pod to other node to mitigate such issue.

**Comment by mloskot** [comment]
@andyzhangx 
> kubelet cannot handle volume reconstruct after node reboot, related issue: https://github.com/kubernetes/kubernetes/issues/117513

Thank you for that reference, it's helpful

> you need to reschedule pod to other node to mitigate such issue

I'm not entirely clear, possibly due to lack of enough experience, on how to do that or what is the best way to handle that.

I use node affinity or taints to force a bunch of pods to common node pool with single node, so I can attach single Azure Disk to multiple pods, my case may be a bit uncommon - this is to ensure Azure Disk attached to single node.

If the rebooted node becomes unhealthy due to the CSI issue, I can apply the following manual intervention:
1. Enable node pool with auto-scaling min=1, max=2
2. Drain failing node `kubectl drain aksxxx000000 --delete-emptydir-data --ignore-daemonsets --force`
3. This will trigger scaling up the node pool, creation of new node and Kubernetes will relocate the pods to the new healthy node

Is there a better production-friendly way to achieve it?
Any feasible automation like policy that will trigger Azure to automatically enable auto-scaling and drain the unhealthy node?

I'd appreciate any help or suggestion.

**Comment by andyzhangx** [comment]
> [@andyzhangx](https://github.com/andyzhangx)
> 
> > kubelet cannot handle volume reconstruct after node reboot, related issue: [kubernetes/kubernetes#117513](https://github.com/kubernetes/kubernetes/issues/117513)
> 
> Thank you for that reference, it's helpful
> 
> > you need to reschedule pod to other node to mitigate such issue
> 
> I'm not entirely clear, possibly due to lack of enough experience, on how to do that or what is the best way to handle that.
> 
> I use node affinity or taints to force a bunch of pods to common node pool with single node, so I can attach single Azure Disk to multiple pods, my case may be a bit uncommon - this is to ensure Azure Disk attached to single node.
> 
> If the rebooted node becomes unhealthy due to the CSI issue, I can apply the following manual intervention:
> 
> 1. Enable node pool with auto-scaling with node counts min=1 max=2
> 2. Drain failing node `kubectl drain aksxxx000000 --delete-emptydir-data --ignore-daemonsets --force`
> 3. This will trigger scaling up the node pool, creation of new node and Kubernetes will relocate the pods to the new healthy node
> 4. Disable auto-scaling with node count = 1
> 
> Is there a better production-friendly way to achieve it? Any feasible automation like policy that will trigger Azure to automatically enable auto-scaling and drain the unhealthy node?
> 
> I'd appreciate any help or suggestion.

@mloskot I think you don't need to enable auto-scale, just scale up a new node first, and then drain the rebooted node.

**Comment by mloskot** [comment]
> you don't need to enable auto-scale, just scale up a new node first, and then drain the rebooted node.

@andyzhangx  It makes sense, of course. Thank you!
